### ISSUE TITLE
Wierd field problems

### ISSUE THREAD

**Issue by SunkenL** [BROADACRES16xFS17MAP/Broad-Acres-16x-Australian-Map#15] opened 2017-10-21 14:41 UTC
When cultivating field 17. there are several spots that dont cultivates. (see picture)
![fsscreen_2017_10_21_16_34_53](https://user-images.githubusercontent.com/24603095/31852789-7a039b82-b67e-11e7-9c9a-3ff3f70edab8.jpg)

Same issue with field 22. (Also courseplay dont register the corner as part of the field)
![fsscreen_2017_10_21_14_25_54](https://user-images.githubusercontent.com/24603095/31852801-af29c390-b67e-11e7-972a-d0d9d2f063fb.jpg)

**Comment by babylon5657** [comment] 2017-10-21 17:52
I am having the same issues with field 17. I started in the SW corner using the cultivator and it was not preparing the ground until i had travelled about 100metres although on those first 100m it was as if the cultivator was working a strip to the left of the cultivator as it was ploughing a track in the road. I also had an issue with it seeming to convert the texture to grass

**Comment by babylon5657** [comment] 2017-10-21 18:21
The issue seems to be with the fertiliser that is on the map (pic1) which is spotty across the map. In pic2 i have ploughed an area in field 21 that straddles the fertilised area and the non fertilised area which you can see due the discolouration on the harvested area.

![20171021191653_1](https://user-images.githubusercontent.com/32924811/31854670-d7f5e5ae-b694-11e7-9549-f9219b6074ff.jpg)

![20171021191517_1](https://user-images.githubusercontent.com/32924811/31854672-dd1743c0-b694-11e7-950a-6a7dd739c538.jpg)

**Comment by BROADACRES16xFS17MAP** [comment] 2017-10-21 20:05
Thanks will have a look. The fields were thoroughly tested and found that some mods caused these issues. We will retest and see if we can reproduce.

**Comment by babylon5657** [comment] 2017-10-21 20:07
I have also tried and it looks as if you cant fertilise at all. Seeders use fertiliser but the actual state wont change. I have even tried just the map with no mods and it makes no differnce

**Comment by BROADACRES16xFS17MAP** [comment] 2017-10-21 21:57
Fixed with new moddesc. (was money script causing havoc (D/L and replace moddesc. New map uploaded.

**Comment by Bundy-Bear** [comment] 2017-10-22 00:17
This is with the new moddesc, As you can see CP doesn't like the corner or even doing it manually

![20171022111049_1](https://user-images.githubusercontent.com/32672100/31856910-7b3a3ce4-b71a-11e7-8305-34d8c15b21c5.jpg)

**Comment by BROADACRES16xFS17MAP** [comment] 2017-10-22 01:21
Start new game and issue will be resolved Bundybear

**Closed as completed by BROADACRES16xFS17MAP** 2017-10-22 01:21 UTC
Labels: FIXED
